### ISSUE TITLE
Home Assistant support

### ISSUE THREAD

**Issue by mindvisionro** [jvitkauskas/pyit600#1]
Hello, congratulations on your efforts!  Everything you have done so far is very helpful, I have been trying for a long time to integrate this system in the home assistant.  I own the salus system with thermostats vs30 do you think they can be integrated in the home assistant?

**Comment by mindvisionro** [comment]
> 
> 
> Hello, congratulations on your efforts! Everything you have done so far is very helpful, I have been trying for a long time to integrate this system in the home assistant. I own the salus system with thermostats vs30 do you think they can be integrated in the home assistant?

>main.py --host ip --euid euid
DEBUG:pyit600:Trying to connect to gateway at id
All climate devices:
{}

It seems is doesn't see my thermostats :(

**Comment by jvitkauskas** [comment]
Hi, I was also working on Home Assistant, but didn't have time to do it.

Can you try sending me the data which is returned in "all_devices" variable for your system here: https://github.com/jvitkauskas/pyit600/blob/003b18ec48720f07f1e573516bdcbc62203ccfef/pyit600/gateway.py#L67

You can try adding print(repr(all_devices)) or something like that below that line

You can mail me if you are not comfortable posting it here or you can edit some potentially sensitive data (mac addresses?) if you want.

**Comment by jvitkauskas** [comment]
Hi, it seems I have forgot to include `await gateway.poll_status()` in the demo. It is added now. Also someone has created homeassistant plugin https://github.com/konradb3/homeassistant_salus
