### ISSUE TITLE
Support a new device SPE600

### ISSUE THREAD

**Issue by George-andrew** [jvitkauskas/pyit600#11]
Dear Julius, 

Please add a new binary device binary (ON/OFF),  
Smart Plug  SPE600 has two working options.

**Comment by jvitkauskas** [comment]
Added support for this library. Will add support for home assistant in the upcoming days.

**Comment by George-andrew** [comment]
@jvitkauskas it doesn't work in home assistant, seems not found in HA

**Comment by jvitkauskas** [comment]
@George-andrew try now. I have updated https://github.com/jvitkauskas/homeassistant_salus
