### ISSUE TITLE
OS600

### ISSUE THREAD

**Issue by peter4200** [jvitkauskas/pyit600#15]
Dear developer 

It looks like the OS600 Windows Device are wrong. It appears as a temperature device and not as a binary switch

SensorDevice(available=True, name='Kontor, sensor', unique_id='xxxxxxxxxxxxxxxx', state='15.76', unit_of_measurement='°C', device_class='temperature', data={'DeviceType': 100, 'Endpoint': 1, 'UniID': '001e5e09021bf7c3'}, manufacturer='SALUS', model='OS600', sw_version='20160620')

**Comment by jvitkauskas** [comment]
Hi, @peter4200 can you send me a full log to email? zadintuvas@gmail.com

**Comment by jvitkauskas** [comment]
@peter4200 try now. I have updated https://github.com/jvitkauskas/homeassistant_salus
