### ISSUE TITLE
ITG500/IT500 request/investigation

### ISSUE THREAD

**Issue by hrford** [jvitkauskas/pyit600#20]
Would like to help with support on ITG500 and the IT500 
Could I clarify if this device is not in scope for this project? If so, is there another project?
If this device is in scope, I have years of experience with Python, Linux, Bash, Network protocols.
Qutie happy to hack and play with WireShark to get network packets.
Otherwise I was going to write a python client for the naff web interface Salus provide.

**Comment by jvitkauskas** [comment]
Took a quick look at iT500 app. It seems to be an entirely different system and also cloud-only. So I don't see which code could be reused from iT600 integration. So it's probably better to create a separate library, unless I am wrong and there is some code which could be shared.

**Comment by jvitkauskas** [comment]
Are you saying Salus provides a fully functional local web interface for controlling iT500 things locally? If that's the case, it's probably best to write client for that.

**Comment by hrford** [comment]
Hey, 
There is a web interface for the IT500, but it goes to their servers, not to the gateway. 

The local gateway has visible UDP traffic, but I guess that also goes to their servers. 

If I was to write a Python client, it would have to emulate a browsing session.

I guess your project is not compatible with my plan as I'm assuming yours goes direct to the local gateway. Is that correct?

Thanks
-- 
Android, K-9 Mail.

**Comment by jvitkauskas** [comment]
Yes, my project uses local communication and does not rely on the cloud. Despite that, I feel that request/response data would be different enough, so that barely any code (if any) could be reused (although, it is only my guess, I don't have any iT500 devices). I can help you with reverse engineering though. You can mail me at zadintuvas@gmail.com
