### ISSUE TITLE
SQ610 works!

### ISSUE THREAD

**Issue by mobopx** [jvitkauskas/pyit600#26]
Salus SQ610 works but on version 0.2.6. Up to version 0.3.0 at all, the HA did not detect devices, neither the SQ610, nor the SQ610RF, nor the VS20WRF.
![image](https://user-images.githubusercontent.com/79940882/135573844-95c29f5d-9bc6-4381-9375-7c17648039a3.png)

**Comment by jvitkauskas** [comment]
Can you please try version 0.3.1?

**Comment by mobopx** [comment]
0.3.1
SQ610 works
VS20WRF works
SQ610RF - i can test on teusday

how to read the humidity entity from SQ610 in HA?

**Comment by jvitkauskas** [comment]
@mobopx try this https://github.com/jvitkauskas/homeassistant_salus/issues/9#issuecomment-770362764
