### ISSUE TITLE
Integration of pyit600 to fhem is also available

### ISSUE THREAD

**Issue by staeblvo** [jvitkauskas/pyit600#30]
Hi jvitkauskas,
there is also a integration of your package to fhem available by the module fhempy from dominikkarall: https://github.com/dominikkarall/fhempy.
Currently there is implementation for climate devices (tested with device VS20WRF) available.
https://github.com/dominikkarall/fhempy/blob/master/FHEM/bindings/python/fhempy/lib/pyit600/README.md

Maybe you want add this info also to your README.md.

BR
Volker

**Comment by jvitkauskas** [comment]
Ok, added this to readme.
