### ISSUE TITLE
Selling my Salus devices on eBay

### ISSUE THREAD

**Issue by jvitkauskas** [jvitkauskas/pyit600#35]
Hi, I am selling my Salus devices on eBay. You may want to bid:

https://www.ebay.de/itm/185684523634
https://www.ebay.de/itm/185684530276
https://www.ebay.de/itm/185684533779
https://www.ebay.de/itm/185684535419
https://www.ebay.de/itm/185684537226
https://www.ebay.de/itm/185684538688
https://www.ebay.de/itm/185684540335

**Comment by falkenhawk** [comment]
@jvitkauskas Since it looks like you divorced salus, may I ask what other system did you migrate your setup to?

**Comment by jvitkauskas** [comment]
I was originally supposed to install some kind of heating control system for my parents. Salus wireless system seemed to be a good choice because they forgot to lay the wires. Unfortunately, they also did not install oversized boxes for underfloor heating controls, so the controllers did not have any space to fit. In the end I've just made something custom with esp32 relays, esphome and those square small xiaomi bluetooth sensors.
